### ISSUE TITLE
2019/01/08 09:47:22 Error building Dashboard: json: cannot unmarshal number into Go struct field GraphDefinition.precision of type string

### ISSUE THREAD

**Issue by scracraft** [promiseofcake/datadog-fetch-hcl#6]
Hi, 

When we run the tool, on one of our timeboards, we get the error:

2019/01/08 09:47:22 Error building Dashboard: json: cannot unmarshal number into Go struct field GraphDefinition.precision of type string

because it is not unmarshalling the number 2 as a string.

Do you know about this bug?

**Comment by scracraft** [comment]
{
                                "definition": {
                                        "autoscale": true,
                                        "precision": 2,
                                        "viz": "query_value",
                                        "requests": [
                                                {
                                                        "q": "avg:new_relic.errors.all.errors_per_minute{application:tax_service_production}",
                                                        "aggregator": "avg",
                                                        "conditional_formats": []
                                                }
                                        ]
                                },
                                "title": "New Relic Errors p/m"
                        },

**Comment by promiseofcake** [comment]
Is this still present after https://github.com/promiseofcake/datadog-fetch-hcl/pull/4?

**Comment by the-great-abby** [comment]
So after we copied the repo locally, and was able to run the following commands:
'go mod init' (so that it will no longer care about GOPATH)
'go build'
the new binary worked

It did not appear to work successfully until we went through the process of pulling down the repo locally and building with the steps outlined above, instead of the normal process of performing an update of 'go get github.com/promiseofcake/datadog-fetch-hcl'.

I am not sure if the datadog-fetch-hcl would also have to be updated in order for the 'go get' method work successfully. 

I hope that helps

**Comment by promiseofcake** [comment]
You should be able to specify the -u flag for go get which will update your locally cloned copy in the GOPATH and install.
